Todo list structure
ecekpo/to_do_list_project pull request #1
Opened 2022-08-11 16:03 UTC by ecekpo

**Added**
- Project Set up with webpack 
*Source files located in src directory
- Iindex.html file 
- index.js file 
- Style.css
- Readme File

2022-08-11 16:18 UTC, leonardodiasb requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @ecekpo, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 

 - No linter errors. ✔️

## Aspects to improve ♻️

- [x] Check the comments under the review.
- [ ] I don't see any Webpack configurations and I cannot install the node modules with `npm install` command. Please use Webpack to build your project.
- 
<img width="1028" alt="image" src="https://user-images.githubusercontent.com/61919617/184180324-ad563efd-cf0f-415d-9782-eaff884abfdf.png">


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-11 16:18 UTC, leonardodiasb commented on README.md
- [ ] Kindly customize the README file for each project you start. Use the correct project name, provide the instructions for a new user to install and use the app with the `npm` commands, if there is no 'Live Demo' don't use a link, etc.

2022-08-11 16:18 UTC, leonardodiasb commented on src/index.js
> +const myArray = [];
- [ ] Kindly add some example tasks to populate your project
 - 
<img width="960" alt="image" src="https://user-images.githubusercontent.com/61919617/184180991-d793107e-4482-4d18-91eb-a71659d2067c.png">

2022-08-11 17:59 UTC, Nemwel-Boniface requested changes
## Hello @ecekpo            :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Great job addressing some of the changes that were requested by a previous reviewer :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

- [ ] I have just realized that you are repeating this project and that is why I have seen there is code for other milestones for the project. In such a situation, you are still required to submit the specific codes for that specific milestone as adding all the codes at once makes it hard when doing reviews of each subsequent milestone.

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-11 17:59 UTC, Nemwel-Boniface commented on src/index.js
> +const myArray = [];
- [ ] As requested by the [previous reviewer](https://github.com/ecekpo/to_do_list_project/pull/1#discussion_r943673640) and according to the [project requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m1_list_structure.md), you are required to  add some example tasks to populate your project.

2022-08-12 18:08 UTC, codecaiine requested changes
Hi @ecekpo , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
- Good use of gitflow :heavy_check_mark: 
- Good commit messages :heavy_check_mark: 

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-12 18:08 UTC, codecaiine commented on src/index.js
- [ ] As requested by two previous reviewers I can't find any example of task populate. Please add some example tasks to populate your project. It is very important to follow the requirement :+1: 
<img width="960" alt="Arrarac" src="https://user-images.githubusercontent.com/6615394/184416233-50149976-8d86-4c76-935b-904749a17cbc.png">


> * [ ]  As requested by the [previous reviewer](https://github.com/ecekpo/to_do_list_project/pull/1#discussion_r943673640) and according to the [project requirements](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m1_list_structure.md), you are required to  add some example tasks to populate your project.

2022-08-12 18:08 UTC, codecaiine commented on src/index.js
> +// eslint-disable-next-line no-unused-vars
- [ ] [OPTIONAL] I noticed that you disable a lot **Eslint** . Please remove the **eslint disable** statement. Because ` Eslint` helps developers to write clean JavaScript codes and adapt best practices when writing the code.  :+1:

2022-08-13 12:33 UTC, Ismailco requested changes
### Hi @ecekpo, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-13 12:33 UTC, Ismailco commented on src/index.js
> +const myArray = [];
- [ ] As the previous reviewer mentioned, kindly add some examples (simples) to the `myArray` array
e.g.
```
const myArray = [
  {
    description: 'An example description in string',
    completed: false,
    index: 1,
  },{
    description: 'An example description in string',
    completed: false,
    index: 2,
  },


```

2022-08-13 12:33 UTC, Ismailco commented on src/index.js
> +// eslint-disable-next-line import/no-cycle
- [ ] [OPTIONAL] Kindly consider fixing linters instead of ignoring the errors, linters can make your code clean

2022-08-13 12:33 UTC, Ismailco commented on modules/clearCompletedTask.js
> +/* eslint-disable import/no-cycle */
- [ ] [OPTIONAL] Kindly consider fixing linters instead of ignoring the errors, linters can make your code clean

2022-08-13 13:56 UTC, FrederickMih approved these changes
# Status: Approved :heavy_check_mark: 

Hi @ecekpo , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-13 14:24 UTC, merged